### PR TITLE
macOS: Add sougou

### PR DESCRIPTION
**Pull request by core-man**

### CODE REVIEW

**Comment by seisman** [comment]
Do we really need it? We may only list software that are directly related to researchees

**Comment by core-man** [comment]
> Do we really need it? We may only list software that are directly related to researchees

You mean those are mainly for researches?

**Comment by seisman** [comment]
> > Do we really need it? We may only list software that are directly related to researchees
> 
> You mean those are mainly for researches?

I think yes. If we list all software we're using, then the list will be too long.

**Comment by core-man** [comment]
> > > Do we really need it? We may only list software that are directly related to researchees
> > 
> > 
> > You mean those are mainly for researches?
> 
> I think yes. If we list all software we're using, then the list will be too long.

Okay.

**Pull request closed without merging**
