### PR TITLE
Fix oneAPI.repo to oneapi.repo for Fedora

### PR DESCRIPTION
**Pull request by seisman**
The repo name is `oneapi.repo`, but the below command is `mv oneAPI.repo /etc/yum.repos.d/`.

### CODE REVIEW

**Review by core-man — COMMENTED** [review]
Shall we use lowercase file names?

**Comment by seisman** [comment]
> Shall we use lowercase file names?

Please see the PR description that I added one minute ago.

**Comment by core-man** [comment]
> > Shall we use lowercase file names?
> 
> Please see the PR description that I added one minute ago.

Let's keep our file name style with lowercase. The official documentation also uses oneapi.

**Comment by seisman** [comment]
> > > Shall we use lowercase file names?
> > 
> > 
> > Please see the PR description that I added one minute ago.
> 
> Let's keep our file name style with lowercase. The official documentation also uses oneapi for some cases in the link.

but they use `sudo mv /tmp/oneAPI.repo /etc/yum.repos.d`.

**Comment by core-man** [comment]
> > > > Shall we use lowercase file names?
> > > 
> > > 
> > > Please see the PR description that I added one minute ago.
> > 
> > 
> > Let's keep our file name style with lowercase. The official documentation also uses oneapi for some cases in the link.
> 
> but they use `sudo mv /tmp/oneAPI.repo /etc/yum.repos.d`.

I think most of us can know oneapi.repo and oneAPI.repo are the same.

**Comment by seisman** [comment]
OK, I will change all to lowercase.

**Review by core-man — APPROVED** [review]

**Pull request merged**
