### PR TITLE
Fix invalid links

### PR DESCRIPTION
**Pull request by core-man**
Addresses https://github.com/seismo-learn/website/issues/57.

See https://software.intel.com/content/www/us/en/develop/articles/installation-guide-for-intel-oneapi-toolkits.html. The new link of `Get Started with the Intel® oneAPI Base Toolkit for macOS` does not work, while the new link for Linux works. 
- old link for macOS: https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/
- new link for macOS: https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html

Let's wait some days to see when the new link for macOS will work. Or we can use https://software.intel.com/content/www/us/en/develop/articles/installation-guide-for-intel-oneapi-toolkits.html for both Linux and macOS instead. Ping @seisman for comments.

### CODE REVIEW

**Comment by seisman** [comment]
I think the new link for macOS works, no?

**Comment by core-man** [comment]
> I think the new link for macOS works, no?

I think it does not work.

> new link for macOS: https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html

**Comment by seisman** [comment]
> > I think the new link for macOS works, no?
> 
> I think it does not work.
> 
> > new link for macOS: [software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html](https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html)

Good. Update the macOS link?

**Comment by core-man** [comment]
But the new link does not work yet

**Comment by seisman** [comment]
I'm confused. What happened when you click the new macOS link?

It's working, no?
image

**Comment by core-man** [comment]
Did you click this one: https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html

See what I get:

**Comment by seisman** [comment]
> Did you click this one: [software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html](https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-hpc-macos/top.html)
> 
> See what I get:
> 

The above link works for me.

**Comment by core-man** [comment]
ggg~ Confused. Let's wait and see if it works for me tomorrow.

**Comment by core-man** [comment]
It works on my macOS, but does not work on CentOS. Let's merge it.

**Review by seisman — APPROVED** [review]

**Pull request merged**
