### PR TITLE
Remove TOC on best practices index page

### PR DESCRIPTION
**Pull request by core-man**
See https://github.com/seismo-learn/seismology101/pull/153#issuecomment-771389496

### CODE REVIEW

**Comment by seisman** [comment]
Weird. I still see them in https://seismo-learn.org/sitepreview/seismo-learn/seismology101/improve-index-1/best-practices/.

**Comment by core-man** [comment]
> Weird. I still see them in https://seismo-learn.org/sitepreview/seismo-learn/seismology101/improve-index-1/best-practices/.

Yes. Seems preview still has some problems.

**Comment by seisman** [comment]
I understand why it doesn't work. I think I have to revert a few recent changes. But it also means that PR previews works for us (maintainers) but not for others (contributors) (see https://github.com/seismo-learn/software/pull/159).

**Comment by core-man** [comment]
> I understand why it doesn't work. I think I have to revert a few recent changes. But it also means that PR previews works for us (maintainers) but not for others (contributors) (see [seismo-learn/software#159](https://github.com/seismo-learn/software/pull/159)).



> I understand why it doesn't work. I think I have to revert a few recent changes. But it also means that PR previews works for us (maintainers) but not for others (contributors) (see [seismo-learn/software#159](https://github.com/seismo-learn/software/pull/159)).

How about we keep both PR and PR_target in Preview action?

**Comment by core-man** [comment]
This PR is also okay. Great～

**Review by seisman — APPROVED** [review]

**Pull request merged**
