### PR TITLE
Add TOC for best practices of file backup

### PR DESCRIPTION
**Pull request by seisman**
Related to #43.

### CODE REVIEW

**Comment by core-man** [comment]
Do we really want to finish this in one PR?

**Comment by seisman** [comment]
> Do we really want to finish this in one PR?

We don't have to.

> Or we may have a TOC here and finish each subsection in individual PRs?

Ok to me.

**Comment by core-man** [comment]
> > Do we really want to finish this in one PR?
> 
> We don't have to.
> 
> > Or we may have a TOC here and finish each subsection in individual PRs?
> 
> Ok to me.

I feel the TOC is okay now.

`rsync` is the fundamental tool and Time Machine is the best for macOS. We may focus on those two if we are free?

We may add work on other tools and add more later if there are more.

**Review by seisman — COMMENTED** [review]
Ok

**Review by core-man — APPROVED** [review]

**Pull request merged**
